### ISSUE TITLE
Handle if ingress already exists

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/throttle#2]
```
[2017-09-29 06:17:34] Error running browsertime Error: Command failed: sudo tc qdisc add dev eth0 ingress
RTNETLINK answers: File exists


RTNETLINK answers: File exists


    at Promise.all.then.arr (/home/phedenskog/.nvm/v6.11.3/lib/node_modules/browsertime/node_modules/@sitespeed.io/throttle/node_modules/execa/index.js:236:11)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by soulgalore** [comment]
We should just remove the filters first, before we try to set them.
