### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by tsunamis1** [sitespeedio/throttle#24]
I get these error when I try to run any throttle command

/usr/lib/node_modules/@sitespeed.io/throttle/lib/index.js:23
  async start(options = {}) {
        ^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/@sitespeed.io/throttle/bin/index.js:6:19)

Details:
npm: 6.9.0
node: v6.17.1

**Comment by soulgalore** [comment]
Hi @tsunamis1 you need to upgrade your node version to 8 (or preferable 10 since that is the LTS).

Best
Peter

**Comment by tsunamis1** [comment]
thanks it works now.
