### ISSUE TITLE
Error when trying to use --localhost without --profile

### ISSUE THREAD

**Issue by jonnysamps** [sitespeedio/throttle#27]
Hi there, thank you so much for this utility, has been very helpful.

I noticed that when running commands like 

```bash
throttle --profile 2g --localhost
```

It works just fine but when I try to specify my own parameters:

```bash
throttle --rtt 200 --localhost
```

I get 
```
(node:32395) UnhandledPromiseRejectionWarning: Error: Localhost on darwin not supported at the moment
    at Object.start (/Users/jsamples/.nvm/versions/node/v8.11.3/lib/node_modules/@sitespeed.io/throttle/lib/index.js:29:17)
    at Object.<anonymous> (/Users/jsamples/.nvm/versions/node/v8.11.3/lib/node_modules/@sitespeed.io/throttle/bin/index.js:99:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

Running on:
MacOS: 10.14.5
Node: 8.11.3
throttle: 0.5.1

Thanks!

**Comment by soulgalore** [comment]
Hi @jonnysamps sorry for the late feedback, the current version only supports adding delay on localhost but lets see if I can fix that.

**Comment by jonnysamps** [comment]
@soulgalore Great!
