### ISSUE TITLE
EPERM: sudo tc qdisc add dev eno1

### ISSUE THREAD

**Issue by kolbasa** [sitespeedio/throttle#35]
Hi, first of all thanks for the project.
However, I can not get the tool up and running.

When I do the following:
```
sudo throttle 3gslow
```

I get the error:
```
UnhandledPromiseRejectionWarning: Error: Command failed with exit code 1 (EPERM): sudo tc qdisc add dev eno1
wlp3s0 ingress
    at makeError (/usr/local/lib/node_modules/@sitespeed.io/throttle/node_modules/execa/lib/error.js:58:11)
    at handlePromise (/usr/local/lib/node_modules/@sitespeed.io/throttle/node_modules/execa/index.js:112:26)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
```

If I use the command:
```
sudo tc qdisc add dev eno1
```
it leads to:
```
RTNETLINK answers: Invalid argument
```

### My network environment: (`ip addr show`)

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether ec:f4:bb:12:34:bf brd ff:ff:ff:ff:ff:ff
    inet 10.10.2.155/23 brd 10.10.3.255 scope global dynamic noprefixroute eno1
       valid_lft 18219sec preferred_lft 18219sec
    inet6 fe80::79bb:ab3c:b096:423f/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
3: wlp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether c4:d9:87:48:c3:cb brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.213/24 brd 192.168.1.255 scope global dynamic noprefixroute wlp3s0
       valid_lft 75819sec preferred_lft 75819sec
    inet6 fe80::d097:c083:b65:c644/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
4: virbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 52:54:00:49:be:1c brd ff:ff:ff:ff:ff:ff
    inet 192.168.122.1/24 brd 192.168.122.255 scope global virbr0
       valid_lft forever preferred_lft forever
5: virbr0-nic: <BROADCAST,MULTICAST> mtu 1500 qdisc fq_codel master virbr0 state DOWN group default qlen 1000
    link/ether 52:54:00:49:be:1c brd ff:ff:ff:ff:ff:ff
6: ifb0: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN group default qlen 32
    link/ether 1e:ad:47:45:94:ae brd ff:ff:ff:ff:ff:ff
    inet6 fe80::1cad:47ff:fe45:94ae/64 scope link 
       valid_lft forever preferred_lft forever
```

### My platform
```
Ubuntu 18.04.3 LTS
Linux COD-MJ3 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by soulgalore** [comment]
Hi @kolbasa sorry for being so late on this one. Did you get out to work?
