### ISSUE TITLE
I am not able to run it in my system.

### ISSUE THREAD

**Issue by itisvignesh** [sitespeedio/throttle#40]
throttle --version            
/usr/local/lib/node_modules/@sitespeed.io/throttle/lib/index.js:23
  async start(options = {}) {
        ^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/@sitespeed.io/throttle/bin/index.js:6:19)

Sytem Info:
System Software Overview:

  System Version:	macOS 10.15.4 (19E287)
  Kernel Version:	Darwin 19.4.0

Hardware Overview:

  Model Name:	iMac
  Model Identifier:	iMac18,3
  Processor Name:	Quad-Core Intel Core i5
  Processor Speed:	3.8 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Memory:	8 GB
  Boot ROM Version:	181.0.0.0.0
  SMC Version (system):	2.41f2

npm -v
6.14.5

**Comment by soulgalore** [comment]
Hi @itisvignesh can you check which NodeJS version you use? I think async was introduced in 10 so you need to have that or a later version.

**Comment by itisvignesh** [comment]
Thanks for the reply,

node -v 
v6.9.4

My bad mine is older, I will update later since other projects depend on nodejs version in my Mac. 
It would be nice if the dependencies were mentioned somewhere.
Now we can close this since it seems not an issue with throttle.
