### ISSUE TITLE
Unable to start throttle command on Windows using NodeJS package

### ISSUE THREAD

**Issue by shrutiseth** [sitespeedio/throttle#89]
Hello @soulgalore !
Am trying network throttling. But getting bellow error message:

seth@testq MINGW64 ~/AppData/Roaming/npm/node_modules
$  throttle --up 330 --down 780 --rtt 200
Error: **Platform win32 not supported**
    at start (file:///C:/Users/seth/AppData/Roaming/npm/node_modules/@sitespeed.io/throttle/lib/index.js:52:13)
    at run (file:///C:/Users/seth/AppData/Roaming/npm/node_modules/@sitespeed.io/throttle/bin/index.js:151:15)
    at file:///C:/Users/seth/AppData/Roaming/npm/node_modules/@sitespeed.io/throttle/bin/index.js:178:7
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12)

seth@testq MINGW64 ~/AppData/Roaming/npm/node_modules

Am using Windows Server 2016 - 64 bit machine and NodeJS package.

**Comment by soulgalore** [comment]
As it says in the header: Simulate slow network connections on **Linux and Mac OS X**.  Maybe you could try this tool: https://calendar.perfplanet.com/2016/testing-with-realistic-networking-conditions/ (winShaper)
